In [2]:
import numpy as np
import pandas as pd




# Load Iris dataset
# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')  # Assuming space-separated data
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values


# Training parameters
learning_rate = 0.1
epochs = 50
num_classes = 3


#learning_rate = 0.1
#input = np.zeros((4,2))
#print(input)
weights = np.random.rand(9)*0.2 - 0.1
print("initial weights:",weights)

epochs = 50

for iter in range(epochs):
    g=0 # activation function
    for i in range(len(input_data)):
        #x1, x2 = input_data[i]
        target_output = output_data[i]
        # add bios 
        inputs = np.append(input_data[i], -1)
        #print(np.shape(weights*inputs))
        g = np.sum(weights*inputs)
        if g>0: y =1
        else: y = 0
        
        error = y - target_output
        weights -= learning_rate * error * inputs
    final_predictions = []
    for i in range(len(input_data)):
            inputs = np.append(input_data[i], -1)        
            final_predictions.append(int(np.dot(inputs, weights) > 0))
    final_accuracy = np.mean(final_predictions == output_data)
    print(f"Accuracy at iteration {iter+1}: {final_accuracy * 100:.2f}%")
    #print(f"Iteration {iter + 1}: Weights = {weights}")



initial weights: [ 0.04303487 -0.07979019  0.09611121 -0.07202961 -0.03503978 -0.07260702
  0.06897995 -0.05113151  0.09114796]


ValueError: operands could not be broadcast together with shapes (9,) (5,) 

In [3]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')  # Assuming space-separated data
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Convert class labels to one-hot encoding
num_classes = len(np.unique(output_data))
output_data_one_hot = np.eye(num_classes)[output_data.astype(int)]

# Training parameters
learning_rate = 0.1
epochs = 50

# Initialize weights with small random values
weights = np.random.rand(input_data.shape[1] + 1, num_classes) * 0.2 - 0.1
print("Initial weights:", weights)

def perceptron_predict(inputs, weights):
    return np.argmax(np.dot(inputs, weights), axis=1)

for iter in range(epochs):
    for i in range(len(input_data)):
        target_output = output_data_one_hot[i]
        inputs = np.append(input_data[i], -1)
        g = np.dot(inputs, weights)
        y = np.argmax(g)
        error = target_output - np.eye(num_classes)[y]
        weights += learning_rate * np.outer(inputs, error)

    if (iter + 1) % 10 == 0:
        predictions = perceptron_predict(np.column_stack((input_data, np.ones(len(input_data)))), weights)
        conf_matrix = confusion_matrix(output_data, predictions)
        accuracy = np.sum(np.diag(conf_matrix)) / np.sum(conf_matrix)
        print(f"Confusion Matrix at iteration {iter + 1}:\n{conf_matrix}")
        print(f"Accuracy at iteration {iter + 1}: {accuracy * 100:.2f}%")

# Final predictions and accuracy
final_predictions = perceptron_predict(np.column_stack((input_data, np.ones(len(input_data)))), weights)
final_conf_matrix = confusion_matrix(output_data, final_predictions)
final_accuracy = np.sum(np.diag(final_conf_matrix)) / np.sum(final_conf_matrix)
print(f"Final Confusion Matrix:\n{final_conf_matrix}")
print(f"Final Accuracy: {final_accuracy * 100:.2f}%")


Initial weights: [[-0.02801365 -0.05668783 -0.0977965 ]
 [ 0.02115132  0.08399792  0.02613516]
 [ 0.02783527  0.01600557  0.02034229]
 [-0.01260749  0.05934031  0.09810696]
 [-0.02488685 -0.05617342 -0.01701836]]
Confusion Matrix at iteration 10:
[[50  0  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 10: 66.67%
Confusion Matrix at iteration 20:
[[50  0  0]
 [ 2  0 48]
 [ 0  0 50]]
Accuracy at iteration 20: 66.67%
Confusion Matrix at iteration 30:
[[50  0  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 30: 66.67%
Confusion Matrix at iteration 40:
[[ 0 50  0]
 [ 0 22 28]
 [ 0  0 50]]
Accuracy at iteration 40: 48.00%
Confusion Matrix at iteration 50:
[[49  1  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 50: 66.00%
Final Confusion Matrix:
[[49  1  0]
 [ 0  0 50]
 [ 0  0 50]]
Final Accuracy: 66.00%


In [5]:
# Manually create one-hot encoding for three classes
output_data_one_hot_manual = np.zeros((len(output_data), 3), dtype=int)

for i, label in enumerate(output_data):
    output_data_one_hot_manual[i, label] = 1

print("Manually created one-hot encoding:\n", output_data_one_hot_manual)



Manually created one-hot encoding:
 [[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 

In [52]:
import numpy as np
import pandas as pd

# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

print(input_data.shape[1])
# One-hot encoding for the output classes
num_classes = 3
output_one_hot = np.eye(num_classes)[output_data.astype(int)]
#print(output_one_hot)


# Training parameters
learning_rate = 0.1
epochs = 5000

# Initialize weights
weights = np.random.rand(input_data.shape[1] + 1, num_classes) * 0.2 - 0.1
print("Initial weights:", weights)
print(len(weights))


# create new inputs with the bios term -1
inputs = np.hstack((input_data, -np.ones((input_data.shape[0], 1))))

#print(inputs)
# Training loop
for iteration in range(epochs):
    for i in range(len(input_data)):
        target_output = output_one_hot[i]
        input = inputs[i]
        #if iteration ==0:
            #print(i,input_data[i])
        #print(inputs)
        # Forward pass
        g = np.dot(input, weights)
        #print(g)

        # Activation function: step function
        # try sigmoid function
        y = np.where(g > 0, 1, 0)

        # Backpropagation
        error = target_output - y
        #print("input[i]",input)
        #print('error[j]:', error)
        # update weights
        for i in range(5):
            for j in range(3):
                weights[i][j] += learning_rate * input[i] * error[j]

        #weights += learning_rate * np.outer(input, error)

    # create new inputs with the bios term -1
    # Evaluate accuracy and print confusion matrix
    final_predictions = np.argmax(np.dot(inputs, weights), axis=1)
    #accuracy = np.mean(final_predictions == output_data)
    #print(f"Iteration {iteration + 1}: Accuracy = {accuracy * 100:.2f}%")
    

        # Compute confusion matrix
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)
    for true_class in range(num_classes):
        for predicted_class in range(num_classes):
            confusion_matrix[true_class, predicted_class] = np.sum((final_predictions == predicted_class) & (output_data == true_class))

    # Compute metrics
    TP = np.diag(confusion_matrix)
    FP = np.sum(confusion_matrix, axis=0) - TP
    FN = np.sum(confusion_matrix, axis=1) - TP
    TN = np.sum(confusion_matrix) - (TP + FP + FN)

    
    recall = TP / (TP + FN)
    precision = TP / (TP + FP)
    accuracy = (TP + TN) / np.sum(confusion_matrix)

    # Print metrics
    print(f"Iteration {iteration + 1}:")
    print(f"Accuracy: {accuracy * 100:.2f}%")
    print("Confusion Matrix:")
    print(confusion_matrix)
    print("Precision:")
    print(precision)
    print("Recall:")
    print(recall)
    print("\n")
    


4
Initial weights: [[-0.04099226 -0.09342233 -0.08076307]
 [ 0.04072134  0.01666453 -0.05560429]
 [-0.05378217 -0.03856531  0.03999079]
 [-0.04838526 -0.0028199  -0.09364812]
 [ 0.08782055 -0.07728381 -0.00632923]]
5
Iteration 1:


notebook-cell.py: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)


TypeError: unsupported format string passed to numpy.ndarray.__format__

In [ ]:
if (iteration + 1) % 10 == 0:
        confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)
        for i in range(num_classes):
            for j in range(num_classes):
                confusion_matrix[i, j] = np.sum((final_predictions == i) & (output_data == j))
        print(f"Iteration {iteration + 1}:")
        print(f"Accuracy = {accuracy * 100:.2f}%")
        print("Confusion Matrix:")
        print(confusion_matrix)

In [4]:
import numpy as np
import pandas as pd

# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Convert class labels to one-hot encoding
num_classes = len(np.unique(output_data))
output_data_one_hot = np.eye(num_classes)[output_data.astype(int)]

# Training parameters
learning_rate = 0.1
epochs = 50

# Initialize weights with small random values
weights = np.random.rand(input_data.shape[1] + 1, num_classes) * 0.2 - 0.1
print("Initial weights:", weights)

def perceptron_predict(inputs, weights):
    return np.argmax(np.dot(inputs, weights), axis=1)

# Confusion matrix function
def compute_confusion_matrix(actual, predicted, num_classes):
    conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
    for a, p in zip(actual, predicted):
        conf_matrix[a, p] += 1
    return conf_matrix

# Accuracy calculation function
def compute_accuracy(conf_matrix):
    correct_predictions = np.sum(np.diag(conf_matrix))
    total_predictions = np.sum(conf_matrix)
    return correct_predictions / total_predictions

for iter in range(epochs):
    for i in range(len(input_data)):
        target_output = output_data_one_hot[i]
        inputs = np.append(input_data[i], -1)
        g = np.dot(inputs, weights)
        y = np.argmax(g)
        error = target_output - np.eye(num_classes)[y]
        weights += learning_rate * np.outer(inputs, error)

    if (iter + 1) % 10 == 0:
        predictions = perceptron_predict(np.column_stack((input_data, np.ones(len(input_data)))), weights)
        conf_matrix = compute_confusion_matrix(output_data, predictions, num_classes)
        accuracy = compute_accuracy(conf_matrix)
        print(f"Confusion Matrix at iteration {iter + 1}:\n{conf_matrix}")
        print(f"Accuracy at iteration {iter + 1}: {accuracy * 100:.2f}%")

# Final predictions and accuracy
final_predictions = perceptron_predict(np.column_stack((input_data, np.ones(len(input_data)))), weights)
final_conf_matrix = compute_confusion_matrix(output_data, final_predictions, num_classes)
final_accuracy = compute_accuracy(final_conf_matrix)
print(f"Final Confusion Matrix:\n{final_conf_matrix}")
print(f"Final Accuracy: {final_accuracy * 100:.2f}%")


Initial weights: [[ 0.08227847  0.03969968 -0.08178391]
 [-0.07904186  0.06004312  0.05724036]
 [ 0.01662619 -0.07078751  0.00832152]
 [ 0.044719    0.00439544  0.06149591]
 [ 0.07035768 -0.020259    0.03797573]]
Confusion Matrix at iteration 10:
[[50  0  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 10: 66.67%
Confusion Matrix at iteration 20:
[[50  0  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 20: 66.67%
Confusion Matrix at iteration 30:
[[49  1  0]
 [ 2  0 48]
 [ 0  0 50]]
Accuracy at iteration 30: 66.00%
Confusion Matrix at iteration 40:
[[ 0 50  0]
 [ 0 28 22]
 [ 0  0 50]]
Accuracy at iteration 40: 52.00%
Confusion Matrix at iteration 50:
[[40 10  0]
 [ 0 21 29]
 [ 0  0 50]]
Accuracy at iteration 50: 74.00%
Final Confusion Matrix:
[[40 10  0]
 [ 0 21 29]
 [ 0  0 50]]
Final Accuracy: 74.00%
