In [50]:
import numpy as np

In [130]:

learning_rate = 0.1
#input = np.zeros((4,2))
#print(input)
weights = np.random.rand(3)*0.2 - 0.1
print("initial weights:",weights)


# or manually choosing 
input_data = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]])

target = np.array([1,0,0,1])


for iter in range(10):
    g=0 # activation function
    for i in range(len(input_data)):
        x1, x2 = input_data[i]
        target_output = target[i]
        # add bios 
        inputs = np.array([x1, x2, -1])
        #print(np.shape(weights*inputs))
        g = np.sum(weights*inputs)
        if g>0: y =1
        else: y = 0
        
        error = y - target_output
        weights -= learning_rate * error * inputs

    print(f"Iteration {iter + 1}: Weights = {weights}")  

initial weights: [ 0.02796892  0.08504677 -0.09141254]
Iteration 1: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 2: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 3: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 4: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 5: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 6: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 7: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 8: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 9: Weights = [0.02796892 0.08504677 0.00858746]
Iteration 10: Weights = [0.02796892 0.08504677 0.00858746]


In [4]:
import numpy as np
import pandas as pd



# Load Pima Indians Diabetes dataset
file_path = "pima-indians-diabetes.csv"
data = pd.read_csv(file_path, header=None)
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values
#print(np.shape(input_data))
#print(output_data)
# Normalize the input data (optional)
#input_data = (input_data - np.mean(input_data, axis=0)) / np.std(input_data, axis=0)


learning_rate = 0.1
#input = np.zeros((4,2))
#print(input)
weights = np.random.rand(9)*0.2 - 0.1
print("initial weights:",weights)


for iter in range(20):
    g=0 # activation function
    for i in range(len(input_data)):
        #x1, x2 = input_data[i]
        target_output = output_data[i]
        # add bios 
        inputs = np.append(input_data[i], -1)
        #print(np.shape(weights*inputs))
        g = np.sum(weights*inputs)
        if g>0: y =1
        else: y = 0
        
        error = y - target_output
        weights -= learning_rate * error * inputs
    final_predictions = []
    for i in range(len(input_data)):
            inputs = np.append(input_data[i], -1)        
            final_predictions.append(int(np.dot(inputs, weights) > 0))
    final_accuracy = np.mean(final_predictions == output_data)
    print(f"Accuracy at iteration {iter+1}: {final_accuracy * 100:.2f}%")
    #print(f"Iteration {iter + 1}: Weights = {weights}")



initial weights: [-0.0584293  -0.05274555 -0.04031769 -0.08093551  0.01789721 -0.02518765
 -0.01404886  0.02484726 -0.09916677]
Accuracy at iteration 1: 61.46%
Accuracy at iteration 2: 61.72%
Accuracy at iteration 3: 59.24%
Accuracy at iteration 4: 54.56%
Accuracy at iteration 5: 69.27%
Accuracy at iteration 6: 61.33%
Accuracy at iteration 7: 60.16%
Accuracy at iteration 8: 60.68%
Accuracy at iteration 9: 68.49%
Accuracy at iteration 10: 61.59%
Accuracy at iteration 11: 62.11%
Accuracy at iteration 12: 60.81%
Accuracy at iteration 13: 62.63%
Accuracy at iteration 14: 61.72%
Accuracy at iteration 15: 54.95%
Accuracy at iteration 16: 66.28%
Accuracy at iteration 17: 61.20%
Accuracy at iteration 18: 60.81%
Accuracy at iteration 19: 64.58%
Accuracy at iteration 20: 65.62%


In [2]:
import numpy as np
import pandas as pd




# Load Iris dataset
# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')  # Assuming space-separated data
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Normalize the input data (optional)
#input_data = (input_data - np.mean(input_data, axis=0)) / np.std(input_data, axis=0)

# Training parameters
learning_rate = 0.1
epochs = 50
num_classes = 3


learning_rate = 0.1
#input = np.zeros((4,2))
#print(input)
weights = np.random.rand(9)*0.2 - 0.1
print("initial weights:",weights)


for iter in range(50):
    g=0 # activation function
    for i in range(len(input_data)):
        #x1, x2 = input_data[i]
        target_output = output_data[i]
        # add bios 
        inputs = np.append(input_data[i], -1)
        #print(np.shape(weights*inputs))
        g = np.sum(weights*inputs)
        if g>0: y =1
        else: y = 0
        
        error = y - target_output
        weights -= learning_rate * error * inputs
    final_predictions = []
    for i in range(len(input_data)):
            inputs = np.append(input_data[i], -1)        
            final_predictions.append(int(np.dot(inputs, weights) > 0))
    final_accuracy = np.mean(final_predictions == output_data)
    print(f"Accuracy at iteration {iter+1}: {final_accuracy * 100:.2f}%")
    #print(f"Iteration {iter + 1}: Weights = {weights}")



initial weights: [-0.03461765 -0.07687942 -0.09346513 -0.01224066 -0.03914625 -0.05451816
  0.09131377 -0.04417163  0.09698539]


ValueError: operands could not be broadcast together with shapes (9,) (5,) 

In [12]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')  # Assuming space-separated data
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Convert class labels to one-hot encoding
num_classes = len(np.unique(output_data))
output_data_one_hot = np.eye(num_classes)[output_data.astype(int)]

# Training parameters
learning_rate = 0.1
epochs = 50

# Initialize weights with small random values
weights = np.random.rand(input_data.shape[1] + 1, num_classes) * 0.2 - 0.1
print("Initial weights:", weights)

def perceptron_predict(inputs, weights):
    return np.argmax(np.dot(inputs, weights), axis=1)

for iter in range(epochs):
    for i in range(len(input_data)):
        target_output = output_data_one_hot[i]
        inputs = np.append(input_data[i], -1)
        g = np.dot(inputs, weights)
        y = np.argmax(g)
        error = target_output - np.eye(num_classes)[y]
        weights += learning_rate * np.outer(inputs, error)

    if (iter + 1) % 10 == 0:
        predictions = perceptron_predict(np.column_stack((input_data, np.ones(len(input_data)))), weights)
        conf_matrix = confusion_matrix(output_data, predictions)
        accuracy = np.sum(np.diag(conf_matrix)) / np.sum(conf_matrix)
        print(f"Confusion Matrix at iteration {iter + 1}:\n{conf_matrix}")
        print(f"Accuracy at iteration {iter + 1}: {accuracy * 100:.2f}%")

# Final predictions and accuracy
final_predictions = perceptron_predict(np.column_stack((input_data, np.ones(len(input_data)))), weights)
final_conf_matrix = confusion_matrix(output_data, final_predictions)
final_accuracy = np.sum(np.diag(final_conf_matrix)) / np.sum(final_conf_matrix)
print(f"Final Confusion Matrix:\n{final_conf_matrix}")
print(f"Final Accuracy: {final_accuracy * 100:.2f}%")


Initial weights: [[-0.042712    0.07528077 -0.02703813]
 [ 0.07317987 -0.0874458   0.03345148]
 [ 0.09419171 -0.02043126 -0.02528005]
 [ 0.06499552  0.06926182 -0.00956765]
 [ 0.0353141   0.05522647  0.04958226]]
Confusion Matrix at iteration 10:
[[50  0  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 10: 66.67%
Confusion Matrix at iteration 20:
[[15 35  0]
 [ 2  0 48]
 [ 0  0 50]]
Accuracy at iteration 20: 43.33%
Confusion Matrix at iteration 30:
[[49  1  0]
 [ 0  0 50]
 [ 0  0 50]]
Accuracy at iteration 30: 66.00%
Confusion Matrix at iteration 40:
[[ 0 50  0]
 [ 0 28 22]
 [ 0  0 50]]
Accuracy at iteration 40: 52.00%
Confusion Matrix at iteration 50:
[[40 10  0]
 [ 0 22 28]
 [ 0  0 50]]
Accuracy at iteration 50: 74.67%
Final Confusion Matrix:
[[40 10  0]
 [ 0 22 28]
 [ 0  0 50]]
Final Accuracy: 74.67%


In [7]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

# Function to define the Perceptron for multi-class classification
def perceptron_predict(inputs, weights):
    return np.argmax(np.dot(inputs, weights))

# Function to train the Perceptron for multi-class classification
def train_perceptron(input_data, output_data, learning_rate, epochs, num_classes):
    num_features = len(input_data[0])
    weights = np.random.rand(num_features + 1, num_classes)  # Initialize weights with small random values (including bias)

    for epoch in range(epochs):
        for i in range(len(input_data)):
            target_output = np.zeros(num_classes)
            target_output[output_data[i]] = 1
            
            inputs = np.concatenate([input_data[i], [1]])  # Adding bias node with value 1
            predicted_output = perceptron_predict(inputs, weights)
            error = target_output - predicted_output
            
            weights += learning_rate * np.outer(inputs, error)

        # Print confusion matrix every few iterations
        if (epoch + 1) % 10 == 0:
            predictions = np.array([perceptron_predict(np.concatenate([input_data[i], [1]]), weights) for i in range(len(input_data))])
            cm = confusion_matrix(output_data, predictions)
            print(f"Iteration {epoch + 1} - Confusion Matrix:")
            print(cm)

    return weights

# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')  # Assuming space-separated data
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Training parameters
learning_rate = 0.1
epochs = 50
num_classes = 3

# Train the Perceptron for multi-class classification
weights = train_perceptron(input_data, output_data, learning_rate, epochs, num_classes)

# Measure final confusion matrix
final_predictions = np.array([perceptron_predict(np.concatenate([input_data[i], [1]]), weights) for i in range(len(input_data))])
final_cm = confusion_matrix(output_data, final_predictions)
print("\nFinal Confusion Matrix:")
print(final_cm)


Iteration 10 - Confusion Matrix:
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0 50]]
Iteration 20 - Confusion Matrix:
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0 50]]
Iteration 30 - Confusion Matrix:
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0 50]]
Iteration 40 - Confusion Matrix:
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0 50]]
Iteration 50 - Confusion Matrix:
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0 50]]

Final Confusion Matrix:
[[ 0  0 50]
 [ 0  0 50]
 [ 0  0 50]]


In [11]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

# Function to define the Perceptron for multi-class classification
def perceptron_predict(inputs, weights):
    return np.argmax(np.dot(inputs, weights))

# Function to one-hot encode class labels
def one_hot_encode(labels, num_classes):
    encoded_labels = np.zeros((len(labels), num_classes))
    for i, label in enumerate(labels):
        encoded_labels[i, label] = 1
    return encoded_labels

# Function to train the Perceptron for multi-class classification
def train_perceptron(input_data, output_data, learning_rate, epochs, num_classes):
    num_features = len(input_data[0])
    weights = np.random.rand(num_features + 1, num_classes)  # Initialize weights with small random values (including bias)

    for epoch in range(epochs):
        for i in range(len(input_data)):
            target_output = one_hot_encode([output_data[i]], num_classes)
            
            inputs = np.concatenate([input_data[i], [1]])  # Adding bias node with value 1
            predicted_output = perceptron_predict(inputs, weights)
            error = target_output - predicted_output
            
            weights += learning_rate * np.outer(inputs, error)

        # Print confusion matrix every few iterations
        if (epoch + 1) % 10 == 0:
            predictions = np.array([perceptron_predict(np.concatenate([input_data[i], [1]]), weights) for i in range(len(input_data))])
            cm = confusion_matrix(output_data, predictions)
            print(f"Iteration {epoch + 1} - Confusion Matrix:")
            print(cm)

    return weights

# Load Iris dataset
file_path = "iris.data"
data = pd.read_csv(file_path, header=None, delimiter=' ')  # Assuming space-separated data
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=42)

# Training parameters
learning_rate = 0.1
epochs = 100
num_classes = 3

# Train the Perceptron for multi-class classification
weights = train_perceptron(X_train, y_train, learning_rate, epochs, num_classes)

# Measure final confusion matrix
final_predictions = np.array([perceptron_predict(np.concatenate([X_test[i], [1]]), weights) for i in range(len(X_test))])
final_cm = confusion_matrix(y_test, final_predictions)
print("\nFinal Confusion Matrix:")
print(final_cm)


Iteration 10 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 20 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 30 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 40 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 50 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 60 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 70 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 80 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 90 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]
Iteration 100 - Confusion Matrix:
[[ 0  0 40]
 [ 0  0 41]
 [ 0  0 39]]

Final Confusion Matrix:
[[ 0  0 10]
 [ 0  0  9]
 [ 0  0 11]]


In [3]:
print("--------Iris dataset---------")

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

# Function to define the Perceptron for multi-class classification
def perceptron_predict(inputs, weights):
    return np.argmax(np.dot(inputs, weights))

# Function to train the Perceptron for multi-class classification
def train_perceptron(input_data, output_data, learning_rate, epochs, num_classes):
    num_features = len(input_data[0])
    weights = np.random.rand(num_features + 1, num_classes)  # Initialize weights with small random values (including bias)

    for epoch in range(epochs):
        for i in range(len(input_data)):
            target_output = np.zeros(num_classes)
            target_output[output_data[i]] = 1
            
            inputs = np.concatenate([input_data[i], [1]])  # Adding bias node with value 1
            predicted_output = perceptron_predict(inputs, weights)
            error = target_output - predicted_output
            
            weights += learning_rate * np.outer(inputs, error)

        # Print confusion matrix every few iterations
        if (epoch + 1) % 10 == 0:
            predictions = np.array([perceptron_predict(np.concatenate([input_data[i], [1]]), weights) for i in range(len(input_data))])
            cm = confusion_matrix(output_data, predictions)
            print(f"Iteration {epoch + 1} - Confusion Matrix:")
            print(cm)

    return weights

# Load Iris dataset
file_path = "iris_dataset.csv"
data = pd.read_csv(file_path, header=None)
input_data = data.iloc[:, :-1].values
output_data = data.iloc[:, -1].values

# Training parameters
learning_rate = 0.1
epochs = 50
num_classes = 3

# Train the Perceptron for multi-class classification
weights = train_perceptron(input_data, output_data, learning_rate, epochs, num_classes)

# Measure final confusion matrix
final_predictions = np.array([perceptron_predict(np.concatenate([input_data[i], [1]]), weights) for i in range(len(input_data))])
final_cm = confusion_matrix(output_data, final_predictions)
print("\nFinal Confusion Matrix:")
print(final_cm)


--------Iris dataset---------


ModuleNotFoundError: No module named 'sklearn'